name: auris
description: "Listening time tracker"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '3.1.2'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.5.0
  flutter_heatmap_calendar: ^1.0.5
  drift: ^2.12.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  drift_dev: ^2.12.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
